default:
	g++ -O3 -std=c++0x main.cpp 
	g++ -O3 -std=c++0x p2z_4d.cpp -o p2z_4d
	g++ -O3 -std=c++0x z2p_4d.cpp -o z2p_4d
	g++ -O3 -std=c++0x gen_zcurve.cpp -o gen_zcurve
	g++ -O3 -std=c++0x gen_zcurve_new.cpp -o gen_zcurve_new
